# Generated by Django 5.2.4 on 2025-07-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfil_type',
            field=models.CharField(choices=[('Administrador', 'Adm'), ('Supervisor', 'Sup'), ('Líder', 'Lid'), ('Auditor', 'Aud')], max_length=20),
        ),
    ]
