# Generated by Django 5.2.4 on 2025-07-12 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria5S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor_name', models.CharField(choices=[('Adm', 'Administração'), ('Produção', 'Produção'), ('Manutenção', 'Manutenção'), ('Ferramentaria', 'Ferramentaria')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255)),
                ('perfil_type', models.CharField(choices=[('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('Líder', 'Líder'), ('Auditor', 'Auditor')], max_length=20)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pilar', models.CharField(choices=[('Seiri', 'Utilização'), ('Seiton', 'Ordenação'), ('Seiso', 'Limpeza'), ('Seiketsu', 'Padronização'), ('Shitsuke', 'Disciplina')], max_length=20)),
                ('nota', models.IntegerField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.auditoria5s')),
            ],
        ),
        migrations.CreateModel(
            name='NaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('criticidade', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], max_length=20)),
                ('data_detectada', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.itemauditoria')),
            ],
        ),
        migrations.CreateModel(
            name='AcaoCorretiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('responsavel', models.CharField(max_length=100)),
                ('prazo', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
                ('nao_conformidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.naoconformidade')),
            ],
        ),
        migrations.AddField(
            model_name='auditoria5s',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.setor'),
        ),
        migrations.AddField(
            model_name='setor',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='auditoria5s',
            name='perfil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_user', to='api.user'),
        ),
    ]
