# Generated by Django 5.2.3 on 2025-07-12 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria5S',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('adm', 'Administração'), ('producao', 'Produção'), ('manutencao', 'Manutenção'), ('ferramentaria', 'Ferramentaria')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('cargo', models.CharField(choices=[('administrador', 'Administrador'), ('supervisor', 'Supervisor'), ('lider', 'Líder'), ('auditor', 'Auditor')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senso', models.CharField(choices=[('seiri', 'Utilização'), ('seiton', 'Ordenação'), ('seiso', 'Limpeza'), ('seiketsu', 'Padronização'), ('shitsuke', 'Disciplina')], max_length=20)),
                ('nota', models.IntegerField(choices=[(1, '1 - Muito Insatisfatório'), (2, '2 - Insatisfatório'), (3, '3 - Regular'), (4, '4 - Bom'), (5, '5 - Excelente')], default=1)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.auditoria5s')),
            ],
        ),
        migrations.CreateModel(
            name='NaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('criticidade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta')], max_length=20)),
                ('data_detectada', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nao_conformidades', to='api.itemauditoria')),
            ],
        ),
        migrations.AddField(
            model_name='auditoria5s',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.setor'),
        ),
        migrations.AddField(
            model_name='setor',
            name='lider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores_liderados', to='api.user'),
        ),
        migrations.AddField(
            model_name='auditoria5s',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='AcaoCorretiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('prazo', models.DateField()),
                ('concluida', models.BooleanField(default=False)),
                ('nao_conformidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_corretivas', to='api.naoconformidade')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
