# Generated by Django 5.2.4 on 2025-09-27 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_perfil_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria5s',
            name='auditor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_como_auditor', to='api.user'),
        ),
        migrations.AlterField(
            model_name='setor',
            name='setor_name',
            field=models.CharField(choices=[('Adm', 'Administração'), ('Produção', 'Produção'), ('Manutenção', 'Manutenção'), ('Ferramentaria', 'Ferramentaria')], max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='perfil_type',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Supervisor', 'Supervisor'), ('Líder', 'Líder'), ('Auditor', 'Auditor')], max_length=20),
        ),
    ]
